version: "3.8"

services:
  mongodb:
    container_name: mongodb
    image: mongo:4.0.20-xenial
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: oauth
    ports:
      - 27017:27017
